---
linear_team_key: APO
github_orgs:
  - apollosproject
  - differential
people:
  michael:
    team: apollos_engineering
    slack_id: U01865757S9
    linear_username: michael.neeley
    github_username: redreceipt
  andy:
    team: apollos_engineering
    slack_id: U080E70RQ4U
    linear_username: andy.smith
    github_username: AndySmith1965
  nathan:
    team: apollos_engineering
    slack_id: U022N4RTD40
    linear_username: nathan
    github_username: nlewis84
  vincent:
    team: unassigned
    slack_id: U15CT1KEF
    linear_username: vincent
    github_username: vinnyjth
  darryl:
    team: apollos_engineering
    slack_id: U07SM59JTD2
    linear_username: darryl
    github_username: darrylyip
  vitor:
    team: apollos_engineering
    slack_id: U07KCR739QR
    linear_username: vitor.lelis
    github_username: vitlelis
  jordan:
    team: unassigned
    slack_id: U03RUFCJRNF
    linear_username: jordan.furdock
    github_username: jfurdock
  austin:
    team: apollos_engineering
    slack_id: U082ES6NT52
    linear_username: austin.witherow
    github_username: awitherow
  nick:
    team: unassigned
    slack_id: U02GJG77A
    linear_username: nick
    github_username: nickw
  brandon:
    team: unassigned
    slack_id: U3V0GB3T8
    linear_username: brandon
    github_username: bkraeling
  conrad:
    team: unassigned
    slack_id: U055MFLMY
    linear_username: conrad
    github_username: conrad-vanl
  lucas:
    team: unassigned
    slack_id: U07P9FP9XB2
    linear_username: lucas
    github_username: diff-eq
  dylan:
    team: unassigned
    slack_id: U03LD9MJLNP
    linear_username: dylan
    github_username: dylan-manchester
  gerry:
    team: unassigned
    slack_id: U025403GG
    linear_username: gerry
    github_username: hellogerard
  zach:
    team: unassigned
    slack_id: U0BLNNPAB
    linear_username: zach
    github_username: solideo-gloria


platforms:
  crossroads:
    lead: dylan
    developers:
      - vitor
  mobile:
    lead: darryl
    developers:
      - vitor
  tv:
    lead: darryl
    developers:
      - vitor
  roku:
    lead: andy
    developers: []
  web:
    lead: nathan
    developers: []
  admin:
    lead: nathan
    developers:
      - austin
  cluster:
    lead: vincent
    developers:
      - darryl
      - vitor
  rock-plugin:
    lead: vincent
    developers: []
  shovel:
    lead: vincent
    developers: []
  transcriptions:
    lead: vincent
    developers: []
